### ISSUE TITLE
Add Dimensions to screen tracking

### ISSUE THREAD

**Issue by philipgiuliani** [Daaru00/nwjs-analytics#1]
Hi, first of all, thanks for this amazing library.

In the Analytics Android SDK i can add custom dimensions for screenViews. Can you extend the library for that?

``` java
Tracker tracker = getDefaultTracker();
tracker.setScreenName("MyAwesomeScreen");
tracker.send(new HitBuilders.ScreenViewBuilder()
    .setCustomDimension(1, "Dimension1Value")
    .build());
```

Could you tell my how do i have to name the params if i do it as a custom event?

Thanks, Philip

**Comment by daaru00** [comment]
Hi, I check on [Google Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#screenView) and I can't seen that option in section App / Screen Tracking. Maybe this option is not implemented in the measurement protocol.

Yes, you can use a custom event, somethings like this:

``` javascript
analytics.event("screenview", "MyAwesomeScreen", "Dimension1Value", "1");
```

if you find any information about  "custom dimension" parameter write me and I'll implement that solution.

**Comment by daaru00** [comment]
Seems there's no solution, can I close this issue?
